# Generated by Django 4.1.7 on 2023-03-25 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scan_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scan",
            old_name="scan_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="scan",
            old_name="scan_currency",
            new_name="currency",
        ),
        migrations.RenameField(
            model_name="scan",
            old_name="scan_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="scan",
            old_name="scan_tax",
            new_name="tax",
        ),
        migrations.RenameField(
            model_name="scan",
            old_name="scan_vendor",
            new_name="vendor",
        ),
    ]
